// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: goalie_stats.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createGoalieStats = `-- name: CreateGoalieStats :one

INSERT INTO GOALIE_GAME_STATS (
    ID,
    GAMEID, 
    CREATED_AT,
    UPDATED_AT,
    TEAM,
    PLAYER_NAME,
    PLAYERID,
    DECISION,
    GOALS_AGAINST,
    SHOTS_AGAINST,
    SAVES, 
    SHUTOUT,
    PEN_MINS,
    TIME_ON_ICE
)
VALUES
($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, gameid, created_at, updated_at, team, player_name, playerid, decision, goals_against, shots_against, saves, save_percent, shutout, pen_mins, time_on_ice
`

type CreateGoalieStatsParams struct {
	ID           uuid.UUID
	Gameid       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Team         string
	PlayerName   string
	Playerid     string
	Decision     sql.NullString
	GoalsAgainst int32
	ShotsAgainst int32
	Saves        int32
	Shutout      bool
	PenMins      int32
	TimeOnIce    int32
}

func (q *Queries) CreateGoalieStats(ctx context.Context, arg CreateGoalieStatsParams) (GoalieGameStat, error) {
	row := q.db.QueryRowContext(ctx, createGoalieStats,
		arg.ID,
		arg.Gameid,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Team,
		arg.PlayerName,
		arg.Playerid,
		arg.Decision,
		arg.GoalsAgainst,
		arg.ShotsAgainst,
		arg.Saves,
		arg.Shutout,
		arg.PenMins,
		arg.TimeOnIce,
	)
	var i GoalieGameStat
	err := row.Scan(
		&i.ID,
		&i.Gameid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Team,
		&i.PlayerName,
		&i.Playerid,
		&i.Decision,
		&i.GoalsAgainst,
		&i.ShotsAgainst,
		&i.Saves,
		&i.SavePercent,
		&i.Shutout,
		&i.PenMins,
		&i.TimeOnIce,
	)
	return i, err
}
