// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type GameResult struct {
	ID             string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DatePlayed     time.Time
	Arena          string
	Attendance     int32
	Duration       time.Time
	HomeTeam       string
	HomeTeamScore  int32
	HomeTeamResult string
	HomeTeamRecord string
	AwayTeam       string
	AwayTeamScore  int32
	AwayTeamResult string
	AwayTeamRecord string
}
