// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type GameResult struct {
	ID             string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DatePlayed     time.Time
	Season         int32
	Arena          string
	Attendance     int32
	Duration       time.Time
	HomeTeam       string
	HomeTeamScore  int32
	HomeTeamResult string
	HomeTeamRecord string
	AwayTeam       string
	AwayTeamScore  int32
	AwayTeamResult string
	AwayTeamRecord string
}

type GoalieGameStat struct {
	ID           uuid.UUID
	GameID       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Team         string
	Season       int32
	PlayerName   string
	PlayerID     string
	Decision     sql.NullString
	GoalsAgainst int32
	ShotsAgainst int32
	Saves        int32
	SavePercent  sql.NullString
	Shutout      int32
	PenMins      int32
	TimeOnIce    int32
}

type GoalieSeasonStat struct {
	UpdatedAt      time.Time
	PlayerID       string
	PlayerName     string
	Team           string
	Season         int32
	GamesPlayed    int32
	Wins           int32
	Losses         int32
	Otlosses       int32
	GoalsAgainst   int32
	GoalsAgaistAvg sql.NullString
	ShotsAgainst   int32
	Saves          int32
	SavePercent    sql.NullString
	Shutouts       int32
	PenMins        int32
	TimeOnIce      int32
}

type PenaltySummary struct {
	ID        uuid.UUID
	GameID    string
	CreatedAt time.Time
	UpdatedAt time.Time
	Period    string
	Time      time.Time
	Team      string
	Player    string
	PlayerID  string
	Penalty   string
	Pim       int32
}

type ProjectMetadatum struct {
	Key   string
	Value string
}

type ScoringSummary struct {
	ID             uuid.UUID
	GameID         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Period         string
	Time           time.Time
	Team           string
	Player         string
	PlayerID       string
	FirstAssist    sql.NullString
	FirstAssistID  sql.NullString
	SecondAssist   sql.NullString
	SecondAssistID sql.NullString
	EmptyNet       bool
}

type Shot struct {
	ID        uuid.UUID
	GameID    string
	CreatedAt time.Time
	UpdatedAt time.Time
	Team      string
	Player    string
	XLoc      int32
	YLoc      int32
	Goal      bool
}

type SkaterGameStat struct {
	ID          uuid.UUID
	GameID      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Team        string
	Season      int32
	PlayerName  string
	PlayerID    string
	Goals       int32
	Assists     int32
	Points      int32
	PlusMinus   int32
	PenMins     int32
	GoalsEv     int32
	GoalsPp     int32
	GoalsSh     int32
	GoalsGw     int32
	AssistsEv   int32
	AssistsPp   int32
	AssistsSh   int32
	Shots       int32
	ShotPercent sql.NullString
	Shifts      int32
	TimeOnIce   int32
}

type SkaterSeasonStat struct {
	UpdatedAt    time.Time
	PlayerID     string
	PlayerName   string
	Team         string
	Season       int32
	GamesPlayed  int32
	Goals        int32
	Assists      int32
	Points       int32
	PlusMinus    int32
	PenMins      int32
	GoalsEv      int32
	GoalsPp      int32
	GoalsSh      int32
	GoalsGw      int32
	AssistsEv    int32
	AssistsPp    int32
	AssistsSh    int32
	Shots        int32
	ShotPercent  sql.NullString
	Shifts       int32
	TimeOnIce    int32
	AvgTimeOnIce sql.NullString
}

type Team struct {
	FullName  string
	ShortName string
}
