// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: reset_db.sql

package database

import (
	"context"
)

const resetGameResults = `-- name: ResetGameResults :exec
DELETE from game_results
`

func (q *Queries) ResetGameResults(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetGameResults)
	return err
}

const resetPenSummaries = `-- name: ResetPenSummaries :exec
DELETE from penalty_summaries
`

func (q *Queries) ResetPenSummaries(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetPenSummaries)
	return err
}

const resetScoringSummaries = `-- name: ResetScoringSummaries :exec
DELETE from scoring_summaries
`

func (q *Queries) ResetScoringSummaries(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetScoringSummaries)
	return err
}

const resetShots = `-- name: ResetShots :exec
DELETE from shots
`

func (q *Queries) ResetShots(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetShots)
	return err
}

const resetSkaterGameStats = `-- name: ResetSkaterGameStats :exec
DELETE from skater_game_stats
`

func (q *Queries) ResetSkaterGameStats(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetSkaterGameStats)
	return err
}
