// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: teams.sql

package database

import (
	"context"
)

const getTeamShortName = `-- name: GetTeamShortName :one
SELECT short_name 
FROM   teams
where  full_name = $1
`

func (q *Queries) GetTeamShortName(ctx context.Context, fullName string) (string, error) {
	row := q.db.QueryRowContext(ctx, getTeamShortName, fullName)
	var short_name string
	err := row.Scan(&short_name)
	return short_name, err
}
