-- +goose Up
CREATE TABLE IF NOT EXISTS SKATER_GAME_STATS (
    ID UUID NOT NULL PRIMARY KEY, 
    GAMEID TEXT NOT NULL REFERENCES GAME_RESULTS(ID),
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    TEAM TEXT NOT NULL,
    PLAYER_NAME TEXT NOT NULL,
    PLAYERID TEXT NOT NULL,
    GOALS INT NOT NULL, 
    ASSISTS INT NOT NULL, 
    POINTS INT NOT NULL, 
    PLUS_MINUS INT NOT NULL,
    PEN_MINS INT NOT NULL,
    GOALS_EV INT NOT NULL, 
    GOALS_PP INT NOT NULL,
    GOALS_SH INT NOT NULL,
    GOALS_GW INT NOT NULL,
    ASSISTS_EV INT NOT NULL,
    ASSISTS_PP INT NOT NULL,
    ASSISTS_SH INT NOT NULL,
    SHOTS INT NOT NULL,
    SHOT_PERCENT NUMERIC(4,3) GENERATED ALWAYS AS (GOALS::NUMERIC / NULLIF(SHOTS, 0)) STORED,
    SHIFTS INT NOT NULL,
    TIME_ON_ICE INT NOT NULL
);

-- +goose Down
DROP TABLE SKATER_GAME_STATS;