-- +goose Up
CREATE TABLE IF NOT EXISTS SKATER_GAME_STATS (
    ID UUID NOT NULL PRIMARY KEY, 
    GAME_ID TEXT NOT NULL REFERENCES GAME_RESULTS(ID) ON DELETE CASCADE,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    TEAM TEXT NOT NULL,
    SEASON INTEGER NOT NULL,
    PLAYER_NAME TEXT NOT NULL,
    PLAYER_ID TEXT NOT NULL,
    GOALS INTEGER NOT NULL, 
    ASSISTS INTEGER NOT NULL, 
    POINTS INTEGER NOT NULL, 
    PLUS_MINUS INTEGER NOT NULL,
    PEN_MINS INTEGER NOT NULL,
    GOALS_EV INTEGER NOT NULL, 
    GOALS_PP INTEGER NOT NULL,
    GOALS_SH INTEGER NOT NULL,
    GOALS_GW INTEGER NOT NULL,
    ASSISTS_EV INTEGER NOT NULL,
    ASSISTS_PP INTEGER NOT NULL,
    ASSISTS_SH INTEGER NOT NULL,
    SHOTS INTEGER NOT NULL,
    SHOT_PERCENT NUMERIC(4,3) GENERATED ALWAYS AS (GOALS::NUMERIC / NULLIF(SHOTS, 0)) STORED,
    SHIFTS INTEGER NOT NULL,
    TIME_ON_ICE INTEGER NOT NULL,

    CONSTRAINT unique_skater_statline UNIQUE (player_id, game_id)
);

-- +goose Down
DROP TABLE SKATER_GAME_STATS;