-- +goose Up
CREATE TABLE IF NOT EXISTS shots (
    ID UUID NOT NULL,
    GAMEID TEXT REFERENCES GAME_RESULTS(ID) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL, 
    TEAM TEXT NOT NULL, 
    PLAYER TEXT NOT NULL, 
    X_LOC INTEGER NOT NULL, 
    Y_LOC INTEGER NOT NULL,
    GOAL BOOLEAN NOT NULL
);

-- +goose Down
DROP TABLE shots;