-- +goose Up
CREATE TABLE IF NOT EXISTS GOALIE_GAME_STATS (
    ID UUID NOT NULL PRIMARY KEY, 
    GAMEID TEXT NOT NULL REFERENCES GAME_RESULTS(ID),
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    TEAM TEXT NOT NULL, 
    PLAYER_NAME TEXT NOT NULL, 
    PLAYERID TEXT NOT NULL,
    DECISION TEXT,
    GOALS_AGAINST INTEGER NOT NULL,
    SHOTS_AGAINST INTEGER NOT NULL,
    SAVES INTEGER NOT NULL,
    SAVE_PERCENT NUMERIC(4,3) GENERATED ALWAYS AS (SAVES::NUMERIC / NULLIF(SHOTS_AGAINST, 0)) STORED,
    SHUTOUT BOOLEAN NOT NULL,
    PEN_MINS INTEGER NOT NULL, 
    TIME_ON_ICE INTEGER NOT NULL
);

-- +goose Down
DROP TABLE GOALIE_GAME_STATS;