-- +goose Up
CREATE TABLE IF NOT EXISTS PROJECT_METADATA (
    KEY TEXT PRIMARY KEY, 
    VALUE TEXT NOT NULL
);

INSERT INTO PROJECT_METADATA (
    KEY, 
    VALUE
) VALUES
(
    'last_scraped_date', '2024/10/01'
);

-- +goose Down
DROP TABLE PROJECT_METADATA;