-- +goose Up
CREATE TABLE IF NOT EXISTS skater_season_stats (
    updated_at TIMESTAMP NOT NULL,
    player_id TEXT NOT NULL,
    player_name TEXT NOT NULL,
    team TEXT NOT NULL,
    season INTEGER NOT NULL,
    games_played INTEGER NOT NULL,
    goals INTEGER NOT NULL, 
    assists INTEGER NOT NULL, 
    points INTEGER NOT NULL, 
    plus_minus INTEGER NOT NULL,
    pen_mins INTEGER NOT NULL,
    goals_ev INTEGER NOT NULL, 
    goals_pp INTEGER NOT NULL,
    goals_sh INTEGER NOT NULL,
    goals_gw INTEGER NOT NULL,
    assists_ev INTEGER NOT NULL,
    assists_pp INTEGER NOT NULL,
    assists_sh INTEGER NOT NULL,
    shots INTEGER NOT NULL,
    shot_percent NUMERIC(4,3) GENERATED ALWAYS AS (goals::NUMERIC / NULLIF(shots, 0)) STORED,
    shifts INTEGER NOT NULL,
    time_on_ice INTEGER NOT NULL, --STORED IN SECONDS
    avg_time_on_ice NUMERIC(10, 3) GENERATED ALWAYS AS (time_on_ice::NUMERIC / NULLIF(GAMES_PLAYED, 0)) STORED,

    CONSTRAINT unique_skater_season_statline UNIQUE (player_id, season, team)
);

CREATE TABLE IF NOT EXISTS goalie_season_stats(
    UPDATED_AT TIMESTAMP NOT NULL,
    PLAYER_ID TEXT NOT NULL,
    PLAYER_NAME TEXT NOT NULL,
    TEAM TEXT NOT NULL, 
    SEASON INTEGER NOT NULL,
    GAMES_PLAYED INTEGER NOT NULL DEFAULT 1,
    WINS INTEGER NOT NULL DEFAULT 0,
    LOSSES INTEGER NOT NULL DEFAULT 0,
    OTLOSSES INTEGER NOT NULL DEFAULT 0,
    GOALS_AGAINST INTEGER NOT NULL DEFAULT 0,
    GOALS_AGAINST_AVG NUMERIC(5,3) GENERATED ALWAYS AS ((GOALS_AGAINST::NUMERIC * 3600.0) / NULLIF(TIME_ON_ICE, 0)) STORED,
    SHOTS_AGAINST INTEGER NOT NULL DEFAULT 0,
    SAVES INTEGER NOT NULL DEFAULT 0,
    SAVE_PERCENT NUMERIC(4,3) GENERATED ALWAYS AS (SAVES::NUMERIC / NULLIF(SHOTS_AGAINST, 0)) STORED,
    SHUTOUTS INTEGER NOT NULL DEFAULT 0,
    PEN_MINS INTEGER NOT NULL DEFAULT 0,   
    TIME_ON_ICE INTEGER NOT NULL, --STORED IN SECONDS

    CONSTRAINT unique_goalie_season_statline UNIQUE (player_id, season, team)
);



-- +goose Down
DROP TABLE skater_season_stats;
DROP TABLE goalie_season_stats;

